site_name: David Han
site_description: Learning is a lifelong journey
site_author: David Han

# Copyright
copyright: "Copyright &copy; 2019 David Han"

nav:
  - Home: index.md
  - About me: aboutme.md
  - Weekly q:
      - 2020: weeklyq/2020.md
  - Python:
      - A First Taste of pathlib: python/a-first-taste-of-pathlib.md
      - Evolution of String Formatting: python/evolution-of-string-formatting.md
  - JavaScript:
      - Array Concatenation: javascript/array-concatenation.md
      - My Journey to Web Scraping: javascript/my-journey-to-web-scraping.md
      - Charting Library in JavaScript: javascript/bubble-chart-in-javascript.md
  - VS Code:
      - Common: vscode/common/common.md
      - Python: vscode/python/python.md
      - JavaScript: vscode/javascript/javascript.md
  - Markets:
      - Short Sell Restriction: markets/short-sell-restriction.md
      - Equities Market Symbology: markets/symbology.md
  - Tips:
      - Cron Job: tips/cron-job.md
      - Vim Color Scheme: tips/vim-color-scheme.md

google_analytics:
  - "UA-140259656-1"
  - "auto"

extra:
  social:
    - type: "github"
      link: "https://github.com/dpkwhan"
    - type: "linkedin"
      link: "https://www.linkedin.com/in/zhaohuihan/"

theme:
  name: "material"
  logo: assets/images/profile-pic.jpg
  favicon: "./assets/images/profile-pic.jpg"
  palette:
    primary: "indigo"
    accent: "deep-orange"
  feature:
    tabs: true

extra_css:
  - assets/css/extra.css
  - assets/css/charting.css
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML"
  - "https://cdnjs.cloudflare.com/ajax/libs/echarts/4.2.1/echarts.min.js"
  - "https://code.highcharts.com/highcharts.js"
  - "https://code.highcharts.com/highcharts-more.js"
  - "https://code.highcharts.com/modules/exporting.js"
  - "https://code.highcharts.com/modules/export-data.js"
  - "https://cdn.plot.ly/plotly-latest.min.js"
  - assets/js/charting.js
  - assets/js/finra.ats.js

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs

site_dir: site
